### PR TITLE
Implement Cartridge Loading

### PR DESCRIPTION
**Pull request by sajattack**
It's only working with 8K cartridges right now. I'm starting to wonder if there's a problem with the bank switching code. I've tried setting memory.basic_on to false and writing 54 to memory location $0001 and in both cases basic still starts up.

### CODE REVIEW

**Comment by kondrak** [comment]
It's possible there's a bug, though I remember testing the emulator with some prgs that specifically disabled Basic and it worked fine. Have you tried running the emulator with the debugger window? Are all the flag statuses reported correctly?

**Comment by sajattack** [comment]
The other possibility is that something in the boot rom that runs after I'm loading the cartridge is re-enabling basic.

**Comment by sajattack** [comment]
Ultimax carts (which are included in the "normal" category of the header but are far from normal), are halting in the 0xf000-0xffff range

**Comment by sajattack** [comment]
Should I just error if I detect an Ultimax cart and call it a day?

**Comment by kondrak** [comment]
I'm not familiar with Ultimax carts but since they are "abnormal" I'd just leave it for now. If it halts (ie. you get a HLT instruction) chances are it's a bug in the CPU emulation somewhere.

**Pull request merged**
